// GET /api/station/lena-line[?show=<show>]
//
// Hybrid Lena-quote endpoint:
//   1. If the queue daemon has logged a Chatter row in the last
//      LIVE_WINDOW_MS, return it as `live` so the public site can show
//      "what Lena just said" with a fresh-timestamp pill.
//   2. Otherwise, pick a random line from the per-show pool JSON and
//      return as `pool`. Pool files are generated by
//      scripts/generate-lena-quote-pool.ts (~150 lines per show).
//
// Show is taken from the `?show=` query param; when missing, derived
// from server-local hour via showForHour(). Returns a hardcoded
// fallback line if both Chatter is empty and the pool file is
// missing — the UI never gets nothing.

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { prisma } from "@/lib/db";
import { showForHour, type ShowBlock as ShowBlockName } from "@/lib/schedule";

export const dynamic = "force-dynamic";

const STATION_SLUG = process.env.STATION_SLUG ?? "numaradio";
const LIVE_WINDOW_MS = 5 * 60 * 1000;
const POOL_DIR = resolve(process.cwd(), "patterns", "lena-quotes");

const SHOW_TO_FILE: Record<string, string> = {
  night_shift: "night-shift.json",
  morning_room: "morning-room.json",
  daylight_channel: "daylight-channel.json",
  prime_hours: "prime-hours.json",
};

const NAME_TO_ENUM: Record<ShowBlockName, string> = {
  "Night Shift": "night_shift",
  "Morning Room": "morning_room",
  "Daylight Channel": "daylight_channel",
  "Prime Hours": "prime_hours",
};

const FALLBACK_LINE = "Always live. Stay a while.";

const poolCache: Partial<Record<string, string[]>> = {};

function loadPool(showSlug: string): string[] {
  if (poolCache[showSlug]) return poolCache[showSlug]!;
  const file = SHOW_TO_FILE[showSlug];
  if (!file) {
    poolCache[showSlug] = [];
    return [];
  }
  const path = resolve(POOL_DIR, file);
  if (!existsSync(path)) {
    poolCache[showSlug] = [];
    return [];
  }
  try {
    const arr = JSON.parse(readFileSync(path, "utf-8"));
    if (!Array.isArray(arr)) {
      poolCache[showSlug] = [];
      return [];
    }
    poolCache[showSlug] = arr.filter((s): s is string => typeof s === "string" && s.trim().length > 0);
    return poolCache[showSlug]!;
  } catch {
    poolCache[showSlug] = [];
    return [];
  }
}

function currentShowSlug(): string {
  const hour = new Date().getHours();
  const slot = showForHour(hour);
  return NAME_TO_ENUM[slot.name];
}

export async function GET(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const requested = url.searchParams.get("show");
  const showSlug = requested && SHOW_TO_FILE[requested] ? requested : currentShowSlug();

  // 1. Live override
  let live: { script: string; airedAt: Date; chatterType: string } | null = null;
  try {
    const station = await prisma.station.findUnique({
      where: { slug: STATION_SLUG },
      select: { id: true },
    });
    if (station) {
      const cutoff = new Date(Date.now() - LIVE_WINDOW_MS);
      const row = await prisma.chatter.findFirst({
        where: { stationId: station.id, airedAt: { gt: cutoff } },
        orderBy: { airedAt: "desc" },
        select: { script: true, airedAt: true, chatterType: true },
      });
      if (row) live = row;
    }
  } catch {
    // DB hiccup — fall through to pool
  }

  if (live) {
    return Response.json(
      {
        source: "live" as const,
        script: live.script,
        atIso: live.airedAt.toISOString(),
        type: live.chatterType,
        show: showSlug,
      },
      { headers: { "Cache-Control": "no-store" } },
    );
  }

  // 2. Pool fallback
  const pool = loadPool(showSlug);
  const script = pool.length > 0 ? pool[Math.floor(Math.random() * pool.length)] : FALLBACK_LINE;
  return Response.json(
    { source: "pool" as const, script, show: showSlug },
    { headers: { "Cache-Control": "no-store" } },
  );
}
