// GET /api/station/lena-line[?show=<show>]
//
// Three-tier Lena-quote endpoint, in priority order:
//   1. LIVE — Chatter row aired in the last LIVE_WINDOW_MS, excluding
//      context_line type. These are real on-air Lena audio (back-
//      announce / shoutout-cta / song-cta / filler) so they're the
//      strongest signal of "what Lena just said."
//   2. CONTEXT — Chatter row with chatterType="context_line" written
//      in the last CONTEXT_WINDOW_MS. Generated by the queue-daemon
//      every 10 min from REAL station state via MiniMax. Text-only
//      (audioUrl=null), referenced as second-priority middle tier.
//      See workers/queue-daemon/context-line.ts + spec
//      docs/superpowers/specs/2026-04-26-lena-context-lines-design.md.
//   3. POOL — random pick from per-show evergreen pool JSON
//      (~150 lines/show, generated by scripts/generate-lena-quote-
//      pool.ts). Always available, the floor.
//
// Show is taken from the `?show=` query param; when missing, derived
// from server-local hour via showForHour(). Returns a hardcoded
// fallback line if all three tiers come up empty — the UI never gets
// nothing.

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { prisma } from "@/lib/db";
import { showForHour, type ShowBlock as ShowBlockName } from "@/lib/schedule";

export const dynamic = "force-dynamic";

const STATION_SLUG = process.env.STATION_SLUG ?? "numaradio";
const LIVE_WINDOW_MS = 5 * 60 * 1000;
// Context-line TTL. Daemon writes a new context line every 10 min, so
// anything older is technically stale. Capping at 10 min so the public
// site falls through to a fresh pool pick (rotates every poll) when the
// most recent context line ages out — that way visitors see content
// move at least once a minute, not stay frozen for 30.
const CONTEXT_WINDOW_MS = 10 * 60 * 1000;
const POOL_DIR = resolve(process.cwd(), "patterns", "lena-quotes");

const SHOW_TO_FILE: Record<string, string> = {
  night_shift: "night-shift.json",
  morning_room: "morning-room.json",
  daylight_channel: "daylight-channel.json",
  prime_hours: "prime-hours.json",
};

const NAME_TO_ENUM: Record<ShowBlockName, string> = {
  "Night Shift": "night_shift",
  "Morning Room": "morning_room",
  "Daylight Channel": "daylight_channel",
  "Prime Hours": "prime_hours",
};

const FALLBACK_LINE = "Always live. Stay a while.";

const poolCache: Partial<Record<string, string[]>> = {};

function loadPool(showSlug: string): string[] {
  if (poolCache[showSlug]) return poolCache[showSlug]!;
  const file = SHOW_TO_FILE[showSlug];
  if (!file) {
    poolCache[showSlug] = [];
    return [];
  }
  const path = resolve(POOL_DIR, file);
  if (!existsSync(path)) {
    poolCache[showSlug] = [];
    return [];
  }
  try {
    const arr = JSON.parse(readFileSync(path, "utf-8"));
    if (!Array.isArray(arr)) {
      poolCache[showSlug] = [];
      return [];
    }
    poolCache[showSlug] = arr.filter((s): s is string => typeof s === "string" && s.trim().length > 0);
    return poolCache[showSlug]!;
  } catch {
    poolCache[showSlug] = [];
    return [];
  }
}

function currentShowSlug(): string {
  const hour = new Date().getHours();
  const slot = showForHour(hour);
  return NAME_TO_ENUM[slot.name];
}

export async function GET(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const requested = url.searchParams.get("show");
  const showSlug = requested && SHOW_TO_FILE[requested] ? requested : currentShowSlug();

  // Tier 1 (live audio chatter) and Tier 2 (context_line) both come
  // from the same Chatter table, just on different windows + filters.
  // Look up the station once, then run both queries in parallel.
  let live: { script: string; airedAt: Date; chatterType: string } | null = null;
  let context: { script: string; airedAt: Date } | null = null;
  try {
    const station = await prisma.station.findUnique({
      where: { slug: STATION_SLUG },
      select: { id: true },
    });
    if (station) {
      const liveCutoff = new Date(Date.now() - LIVE_WINDOW_MS);
      const contextCutoff = new Date(Date.now() - CONTEXT_WINDOW_MS);
      const [liveRow, contextRow] = await Promise.all([
        prisma.chatter.findFirst({
          where: {
            stationId: station.id,
            airedAt: { gt: liveCutoff },
            chatterType: { not: "context_line" },
          },
          orderBy: { airedAt: "desc" },
          select: { script: true, airedAt: true, chatterType: true },
        }),
        prisma.chatter.findFirst({
          where: {
            stationId: station.id,
            airedAt: { gt: contextCutoff },
            chatterType: "context_line",
          },
          orderBy: { airedAt: "desc" },
          select: { script: true, airedAt: true },
        }),
      ]);
      if (liveRow) live = liveRow;
      if (contextRow) context = contextRow;
    }
  } catch {
    // DB hiccup — fall through to pool
  }

  if (live) {
    return Response.json(
      {
        source: "live" as const,
        script: live.script,
        atIso: live.airedAt.toISOString(),
        type: live.chatterType,
        show: showSlug,
      },
      { headers: { "Cache-Control": "no-store" } },
    );
  }

  if (context) {
    return Response.json(
      {
        source: "context" as const,
        script: context.script,
        atIso: context.airedAt.toISOString(),
        show: showSlug,
      },
      { headers: { "Cache-Control": "no-store" } },
    );
  }

  // Tier 3 — pool floor
  const pool = loadPool(showSlug);
  const script = pool.length > 0 ? pool[Math.floor(Math.random() * pool.length)] : FALLBACK_LINE;
  return Response.json(
    { source: "pool" as const, script, show: showSlug },
    { headers: { "Cache-Control": "no-store" } },
  );
}
